[[redirects]]
  from = "/*"
  to = "/404/404.html"
  status = 404

[build]
  functions = "netlify/functions" # Path to your functions directory

[context.production.environment]
  MONGODB_URI = "mongodb+srv://melodyfuseradio:admin@mfusedb.fd1cd.mongodb.net/"
